<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>
		<RootNamespace>BLMapCheck</RootNamespace>
		<AssemblyName>BLMapCheck</AssemblyName>
		<OutputType>Library</OutputType>
		<Deterministic>true</Deterministic>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="beatleader-analyzer\**" />
	  <Compile Remove="beatleader-parser\**" />
	  <Compile Remove="JoshaParity\**" />
	  <EmbeddedResource Remove="beatleader-analyzer\**" />
	  <EmbeddedResource Remove="beatleader-parser\**" />
	  <EmbeddedResource Remove="JoshaParity\**" />
	  <None Remove="beatleader-analyzer\**" />
	  <None Remove="beatleader-parser\**" />
	  <None Remove="JoshaParity\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Analyzer">
	    <HintPath>..\SubModule\beatleader-analyzer\beatleader-analyzer\obj\Release\netstandard2.1\Analyzer.dll</HintPath>
	  </Reference>
	  <Reference Include="JoshaParity">
	    <HintPath>..\SubModule\JoshaParity\JoshaParity\obj\Release\netstandard2.1\JoshaParity.dll</HintPath>
	  </Reference>
	  <Reference Include="Parser">
	    <HintPath>..\SubModule\beatleader-parser\beatleader-parser\obj\Release\netstandard2.1\Parser.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y /d  &quot;$(TargetPath)&quot; &quot;$(ChroMapperDir)\Plugins&quot;" />
	</Target>
</Project>