using System.Collections.Generic;

namespace ChroMapper_LightModding.Models
{
    public enum CommentTypesEnum
    {
        Suggestion,
        Unsure,
        Issue,
        Info
    }

    public class Comment
    {
        public string Id { get; set; } = null!;
        public float StartBeat { get; set; }

        public List<SelectedObject> Objects { get; set; }

        public CommentTypesEnum Type { get; set; }

        public string Message { get; set; } = null!;
        public string Response { get; set; } = "";

        public bool MarkAsSuppressed { get; set; } = false; // was MarkAsRead, will now mean MarkAsSuppressed
        public bool IsAutogenerated { get; set; } = false;
    }
}
