<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<LangVersion>latest</LangVersion>
		<RootNamespace>ChroMapper_LightModding</RootNamespace>
		<AssemblyName>ChroMapper-AutoModder</AssemblyName>
		<OutputType>Library</OutputType>
		<Deterministic>true</Deterministic>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<DebugSymbols>true</DebugSymbols>
		<DebugType>full</DebugType>
		<Optimize>false</Optimize>
		<OutputPath>bin\Debug\</OutputPath>
		<DefineConstants>DEBUG;TRACE</DefineConstants>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DebugType>pdbonly</DebugType>
		<Optimize>true</Optimize>
		<OutputPath>bin\Release\</OutputPath>
		<DefineConstants>TRACE</DefineConstants>
		<WarningLevel>4</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="Analyzer">
		  <HintPath>..\SubModule\beatleader-analyzer\beatleader-analyzer\obj\Release\netstandard2.1\Analyzer.dll</HintPath>
		</Reference>
		<Reference Include="FileBrowser">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\FileBrowser.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="JoshaParity">
		  <HintPath>..\SubModule\JoshaParity\JoshaParity\obj\Release\netstandard2.1\JoshaParity.dll</HintPath>
		</Reference>
		<Reference Include="Main">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\Main.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Plugins">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\Plugins.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unity.InputSystem">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\Unity.InputSystem.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="Unity.TextMeshPro">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\Unity.TextMeshPro.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.CoreModule">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\UnityEngine.CoreModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.ImageConversionModule">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\UnityEngine.ImageConversionModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.IMGUIModule">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\UnityEngine.IMGUIModule.dll</HintPath>
			<Private>false</Private>
		</Reference>
		<Reference Include="UnityEngine.UI">
			<HintPath>$(ChroMapperDir)\ChroMapper_Data\Managed\UnityEngine.UI.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="NVorbis" Version="0.10.5" />
		<PackageReference Include="ricaun.ILRepack" Version="1.0.3">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="System.IO.Compression" Version="4.3.0" />
		<PackageReference Include="System.IO.Compression.ZipFile" Version="4.3.0" />
		<PackageReference Include="System.Text.Json" Version="9.0.9" />
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Assets\Icon.png" />
		<EmbeddedResource Include="manifest.json" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BLMapCheck\BLMapCheck.csproj" />
	  <ProjectReference Include="..\SubModule\beatleader-analyzer\Parser\beatleader-parser\Parser.csproj" />
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /y /d  &quot;$(TargetPath)&quot; &quot;$(ChroMapperDir)\Plugins&quot;" />
	</Target>
</Project>